### ISSUE TITLE
but it works on multidimensional spars  data ?

### ISSUE THREAD

**Issue by Sandy4321** [GRAAL-Research/MinCq#2]
looks great thanks
but it works on multidimensional spars  data ?

**Comment by jeanfrancisroy** [comment]
If I recall correctly, this implementation was done using Numpy arrays, so they will be dense and might be problematic if your data is very sparse.

However, the code is quite simple, you might be able to use sparse vectors with a couple changes.

**Comment by Sandy4321** [comment]
thanks for soon answer
actually, I meant the structure of data not data representation 
the question is about conceptual ability to work with spars data
for example 10 million rows, when each row has 10000 columns, but each column has 30 ones and 9970 zeros??
So big observation matrix with 10000 features?
Thanks

**Comment by jeanfrancisroy** [comment]
Might I ask if you read the paper? This algorithm is an ensemble method of hypotheses (voters), defined a priori (by you). So it's independent on the sparseness of your data: it will combine voters of your choice.

For instance, if you want to combine decision trees, it's the decision tree algorithm that need to deal with your sparse features, not MinCq itself. You would build your trees (using any library), then use MinCq to build a majority vote out of them. If you use one of the default voter generators that I implemented in the examples, you will definitely run into issues, as I didn't use a data representation (nor a choice of voters) that will play nicely with your data. If we go back to my example of decision trees, you might want to use Scikit-Learn, as it handles sparse data very well. https://scikit-learn.org/stable/modules/tree.html

Finally, note that the quadratic program defined in the paper could be solved by any solver (in this repo I use CVXOPT), so if you run into issues with the quantity of data samples that you have, you might as well solve the QP with different solvers that are designed to scale more efficiently with the size of the data. You might also want to take a look at CqBoost (http://proceedings.mlr.press/v51/roy16.pdf), an iterative version of MinCq that will scale better if you use many many voters.

**Comment by Sandy4321** [comment]
Thank you very much for an answer
regarding to A Column Generation Bound Minimization Approach with
PAC-Bayesian Generalization Guarantees
is there code implementation shared to check if this material reproducible?

**Comment by jeanfrancisroy** [comment]
Unfortunately I never had the time to clean my code so it stops depending on the research lab's library. However note that the pseudo-code is easy to follow, and that each iteration solves a small MinCq problem (with fewer voters) so it's not hard to implement.

**Comment by Sandy4321** [comment]
good news
may you share this code
it is always good to understand from code what is happen,  verbose explanations always loose slmthing  you know
thank you very much in advance
