### ISSUE TITLE
may you share written simple idea level explanation of theory behind this

### ISSUE THREAD

**Issue by Sandy4321** [GRAAL-Research/MinCq#3]
may you share written simple idea level explanation of theory behind this

**Comment by jeanfrancisroy** [comment]
A simple explanation to "why the algorithm works" is that given a set of hypotheses that individually perform poorly on the data (say, small decision trees), the theory says that we should combine them by giving weight such as the individual hypotheses are maximally decorrelated. This is what the algorithm optimizes.

Now, the theory is more complicated, but you have two references in Readme.md. I suggest the JMLR paper, which is much more pedagogic than the ICML one. It's a long read, but the theory can't be much more simplified than in this paper :-)
